apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ibrahimhefny/cloud-native-devops-platform.git
    targetRevision: main
    path: k8s   # الفولدر اللي فيه manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: voting

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
